import type { ProviderPreset } from "./types";

/**
 * Built-in provider presets.
 *
 * Weighted toward image and video generation, since that is what the canvas does. Chat models
 * are included only where they serve prompt rewriting.
 *
 * Model lists are a starting point, not an inventory — vendors ship models faster than this file
 * can track. The "fetch models" button in provider settings queries the provider's own
 * `/v1/models` and is the authoritative source; these presets exist so a new user has something
 * usable the moment they paste a key.
 */

const openai: ProviderPreset = {
  builtinId: "openai",
  version: 1,
  name: "OpenAI",
  description: "GPT 与 DALL·E / Sora 系列",
  type: "openai-chat",
  defaultBaseUrl: "https://api.openai.com/v1",
  homepage: "https://openai.com",
  apiKeyUrl: "https://platform.openai.com/api-keys",
  iconSlug: "openai",
  defaultModels: [
    {
      modelKey: "gpt-image-1",
      name: "GPT Image 1",
      category: "image",
      type: "openai-images",
      enabled: true,
    },
    {
      modelKey: "sora-2",
      name: "Sora 2",
      category: "video",
      type: "openai-video",
      enabled: true,
    },
    {
      modelKey: "gpt-4o-mini",
      name: "GPT-4o mini",
      category: "chat",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
  ],
};

const anthropic: ProviderPreset = {
  builtinId: "anthropic",
  version: 1,
  name: "Anthropic",
  description: "Claude 系列，用于提示词优化",
  type: "anthropic",
  defaultBaseUrl: "https://api.anthropic.com",
  homepage: "https://anthropic.com",
  apiKeyUrl: "https://console.anthropic.com/settings/keys",
  iconSlug: "claude",
  defaultModels: [
    {
      modelKey: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-haiku-4-5-20251001",
      name: "Claude Haiku 4.5",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
  ],
};

const google: ProviderPreset = {
  builtinId: "google",
  version: 1,
  name: "Google Gemini",
  description: "Gemini 与 Imagen / Veo 系列",
  type: "gemini",
  defaultBaseUrl: "https://generativelanguage.googleapis.com",
  homepage: "https://ai.google.dev",
  apiKeyUrl: "https://aistudio.google.com/apikey",
  iconSlug: "gemini",
  defaultModels: [
    {
      modelKey: "gemini-3-pro-image-preview",
      name: "Gemini 3 Pro Image",
      category: "image",
      type: "gemini",
      enabled: true,
    },
    {
      modelKey: "imagen-4.0-generate-001",
      name: "Imagen 4",
      category: "image",
      type: "gemini",
      enabled: true,
    },
    {
      modelKey: "gemini-2.5-flash",
      name: "Gemini 2.5 Flash",
      category: "chat",
      contextLength: 1_048_576,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
  ],
};

const volcengine: ProviderPreset = {
  builtinId: "volcengine",
  version: 1,
  name: "火山方舟",
  description: "字节跳动 · Seedream 图片与 Seedance 视频",
  type: "openai-chat",
  defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
  homepage: "https://www.volcengine.com/product/ark",
  apiKeyUrl: "https://console.volcengine.com/ark",
  iconSlug: "doubao",
  defaultModels: [
    {
      modelKey: "doubao-seedream-4-0-250828",
      name: "Seedream 4.0",
      category: "image",
      type: "openai-images",
      enabled: true,
    },
    {
      modelKey: "doubao-seedance-1-0-pro-250528",
      name: "Seedance 1.0 Pro",
      category: "video",
      type: "seedance-video",
      enabled: true,
    },
  ],
};

const siliconflow: ProviderPreset = {
  builtinId: "siliconflow",
  version: 1,
  name: "SiliconFlow",
  description: "硅基流动 · 开源模型聚合",
  type: "openai-chat",
  defaultBaseUrl: "https://api.siliconflow.cn/v1",
  homepage: "https://siliconflow.cn",
  apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
  iconSlug: "siliconcloud",
  defaultModels: [
    {
      modelKey: "Kwai-Kolors/Kolors",
      name: "Kolors",
      category: "image",
      type: "openai-images",
      enabled: true,
    },
    {
      modelKey: "Qwen/Qwen2.5-7B-Instruct",
      name: "Qwen2.5 7B",
      category: "chat",
      contextLength: 32_768,
      enabled: true,
    },
  ],
};

const xai: ProviderPreset = {
  builtinId: "xai",
  version: 1,
  name: "xAI",
  description: "Grok 与 Aurora 图片模型",
  type: "openai-chat",
  defaultBaseUrl: "https://api.x.ai/v1",
  homepage: "https://x.ai",
  apiKeyUrl: "https://console.x.ai",
  iconSlug: "grok",
  defaultModels: [
    {
      modelKey: "grok-2-image-1212",
      name: "Grok 2 Image",
      category: "image",
      type: "openai-images",
      enabled: true,
    },
  ],
};

const openrouter: ProviderPreset = {
  builtinId: "openrouter",
  version: 1,
  name: "OpenRouter",
  description: "多厂商聚合，单一 Key 访问",
  type: "openai-chat",
  defaultBaseUrl: "https://openrouter.ai/api/v1",
  homepage: "https://openrouter.ai",
  apiKeyUrl: "https://openrouter.ai/keys",
  iconSlug: "openrouter",
  defaultModels: [],
};

const deepseek: ProviderPreset = {
  builtinId: "deepseek",
  version: 1,
  name: "DeepSeek",
  description: "DeepSeek 对话与推理模型",
  type: "openai-chat",
  defaultBaseUrl: "https://api.deepseek.com/v1",
  homepage: "https://deepseek.com",
  apiKeyUrl: "https://platform.deepseek.com/api_keys",
  iconSlug: "deepseek",
  defaultModels: [
    {
      modelKey: "deepseek-chat",
      name: "DeepSeek Chat",
      category: "chat",
      contextLength: 65_536,
      maxOutputTokens: 8_192,
      supportsFunctionCall: true,
      enabled: true,
    },
  ],
};

const ollama: ProviderPreset = {
  builtinId: "ollama",
  version: 1,
  name: "Ollama",
  description: "本地模型，无需 API Key",
  type: "openai-chat",
  defaultBaseUrl: "http://localhost:11434/v1",
  homepage: "https://ollama.com",
  requiresApiKey: false,
  iconSlug: "ollama",
  defaultModels: [],
};

const routinAi: ProviderPreset = {
  builtinId: "routin-ai",
  version: 2,
  name: "Routin AI",
  description: "多模型聚合，OpenAI 兼容协议",
  type: "openai-chat",
  defaultBaseUrl: "https://api.routin.ai/v1",
  homepage: "https://routin.ai",
  apiKeyUrl: "https://routin.ai/dashboard/api-keys",
  defaultModels: [
    {
      modelKey: "gpt-5.6-terra",
      name: "GPT 5.6 Terra",
      category: "chat",
      type: "openai-responses",
      contextLength: 372_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-fable-5",
      name: "Claude Fable 5",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-opus-5",
      name: "Claude Opus 5",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5-pro",
      name: "MiMo V2.5 Pro",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "kimi-k3",
      name: "Kimi K3",
      category: "chat",
      type: "anthropic",
      contextLength: 1_048_576,
      maxOutputTokens: 131_072,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "kimi-k2.7-code-highspeed",
      name: "Kimi K2.7 Code HighSpeed",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "kimi-k2.6",
      name: "Kimi K2.6",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "kimi-k2.5",
      name: "Kimi K2.5",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "glm-5.2",
      name: "GLM 5.2",
      category: "chat",
      contextLength: 1_000_000,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5",
      name: "MiMo V2.5",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 131_072,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5-pro-ultraspeed",
      name: "MiMo V2.5 Pro UltraSpeed",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-4o",
      name: "GPT-4o",
      category: "chat",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gpt-4o-mini",
      name: "GPT-4o Mini",
      category: "chat",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "o1",
      name: "o1",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "o1-pro",
      name: "o1 Pro",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "o1-mini",
      name: "o1 Mini",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "o3-mini",
      name: "o3 Mini",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "o3-pro",
      name: "o3 Pro",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "o4-mini",
      name: "o4 Mini",
      category: "chat",
      contextLength: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-4.1",
      name: "GPT-4.1",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gpt-4.1-mini",
      name: "GPT-4.1 Mini",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 32_768,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gpt-4.1-nano",
      name: "GPT-4.1 Nano",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 32_768,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5-chat",
      name: "GPT-5 Chat",
      category: "chat",
      type: "openai-responses",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.1-chat",
      name: "GPT-5.1 Chat",
      category: "chat",
      type: "openai-responses",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.2-chat",
      name: "GPT-5.2 Chat",
      category: "chat",
      type: "openai-responses",
      contextLength: 128_000,
      maxOutputTokens: 16_384,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5",
      name: "GPT 5",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.1",
      name: "GPT 5.1",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.2",
      name: "GPT 5.2",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.3-codex",
      name: "GPT 5.3 Codex",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.4-nano",
      name: "GPT 5.4 Nano",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.4-mini",
      name: "GPT 5.4 Mini",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.4",
      name: "GPT 5.4",
      category: "chat",
      type: "openai-responses",
      contextLength: 268_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.5",
      name: "GPT 5.5",
      category: "chat",
      type: "openai-responses",
      contextLength: 268_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.6-luna",
      name: "GPT 5.6 Luna",
      category: "chat",
      type: "openai-responses",
      contextLength: 372_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.6-sol",
      name: "GPT 5.6 Sol",
      category: "chat",
      type: "openai-responses",
      contextLength: 372_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5-pro",
      name: "GPT 5 Pro",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 272_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.2-pro",
      name: "GPT 5.2 Pro",
      category: "chat",
      type: "openai-responses",
      contextLength: 400_000,
      maxOutputTokens: 272_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gpt-5.3-codex-spark",
      name: "GPT 5.3 Codex Spark",
      category: "chat",
      type: "openai-responses",
      contextLength: 128_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5-tts",
      name: "MiMo V2.5 TTS",
      category: "speech",
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5-tts-voicedesign",
      name: "MiMo V2.5 TTS VoiceDesign",
      category: "speech",
      enabled: true,
    },
    {
      modelKey: "mimo-v2.5-tts-voiceclone",
      name: "MiMo V2.5 TTS VoiceClone",
      category: "speech",
      enabled: true,
    },
    {
      modelKey: "gpt-4o-transcribe",
      name: "GPT-4o Transcribe",
      category: "speech",
      enabled: true,
    },
    {
      modelKey: "gpt-4o-mini-transcribe",
      name: "GPT-4o Mini Transcribe",
      category: "speech",
      enabled: true,
    },
    {
      modelKey: "gpt-image-1.5",
      name: "GPT Image 1.5",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "gpt-image-2",
      name: "GPT Image 2",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "gpt-image-2-all",
      name: "GPT Image 2 All",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "gpt-image-2-fast",
      name: "GPT Image 2 Fast",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "gpt-image-2-4k",
      name: "GPT Image 2 4K",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "grok-imagine-image-quality",
      name: "Grok Imagine Image Quality",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "grok-imagine-image",
      name: "Grok Imagine Image",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "grok-imagine-video",
      name: "Grok Imagine Video",
      category: "video",
      type: "xai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "grok-imagine-video-1.5-preview",
      name: "Grok Imagine Video 1.5 Preview",
      category: "video",
      type: "xai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sora-2",
      name: "Sora 2",
      category: "video",
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-mini-720p",
      name: "SD Mini 720p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-mini-480p",
      name: "SD Mini 480p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-fast-720p",
      name: "SD Fast 720p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-fast-480p",
      name: "SD Fast 480p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-2.0-480p",
      name: "SD 2.0 480p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-2.0-720p",
      name: "SD 2.0 720p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "sd-2.0-1080p",
      name: "SD 2.0 1080p",
      category: "video",
      introducedInVersion: 2,
      type: "openai-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedance-2-0-260128",
      name: "Seedance 2.0",
      category: "video",
      type: "seedance-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedance-2-0-fast-260128",
      name: "Seedance 2.0 Fast",
      category: "video",
      type: "seedance-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedance-2-0-mini-260615",
      name: "Seedance 2.0 mini",
      category: "video",
      type: "seedance-video",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "MiniMax-M3",
      name: "MiniMax M3",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "MiniMax-M2.7",
      name: "MiniMax M2.7",
      category: "chat",
      type: "anthropic",
      contextLength: 204_800,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "MiniMax-M2.7-highspeed",
      name: "MiniMax M2.7 Highspeed",
      category: "chat",
      type: "anthropic",
      contextLength: 204_800,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "MiniMax-M2.5",
      name: "MiniMax M2.5",
      category: "chat",
      type: "anthropic",
      contextLength: 204_800,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "MiniMax-M2.5-highspeed",
      name: "MiniMax M2.5 Highspeed",
      category: "chat",
      type: "anthropic",
      contextLength: 204_800,
      maxOutputTokens: 131_072,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "deepseek-v4-flash",
      name: "DeepSeek V4 Flash",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 384_000,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 384_000,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3.5-flash",
      name: "Gemini 3.5 Flash",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 65_536,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3-flash-preview",
      name: "Gemini 3 Flash Preview",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 65_536,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3-pro-preview",
      name: "Gemini 3 Pro Preview",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 65_536,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro Preview",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 65_536,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3.1-flash-lite-preview",
      name: "Gemini 3.1 flash Lite Preview",
      category: "chat",
      contextLength: 1_048_576,
      maxOutputTokens: 65_536,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3.1-flash-image-preview",
      name: "Gemini 3.1 Flash Image Preview",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "gemini-3-pro-image-preview",
      name: "Gemini 3 Pro Image Preview",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-0-code-preview-260215",
      name: "Doubao Seed 2.0 Code Preview (260215)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-code-preview-latest",
      name: "Doubao Seed Code Preview (Latest)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-0-mini-260215",
      name: "Doubao Seed 2.0 Mini (260215)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2.0-code",
      name: "Doubao Seed 2.0 Code",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-0-pro-260215",
      name: "Doubao Seed 2.0 Pro (260215)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-0-lite-260215",
      name: "Doubao Seed 2.0 Lite (260215)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-evolving",
      name: "Doubao Seed Evolving",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-1-pro-260628",
      name: "Doubao Seed 2.1 Pro (260628)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seed-2-1-turbo-260628",
      name: "Doubao Seed 2.1 Turbo (260628)",
      category: "chat",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedream-4-5-251128",
      name: "Doubao Seedream 4.5 (251128)",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedream-4-0-250828",
      name: "Doubao Seedream 4.0 (250828)",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedream-5-0-260128",
      name: "Doubao Seedream 5.0 (260128)",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "doubao-seedream-3-0-t2i-250415",
      name: "Doubao Seedream 3.0 T2I (250415)",
      category: "image",
      type: "openai-images",
      supportsVision: true,
      enabled: true,
    },
    {
      modelKey: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-opus-4-6",
      name: "Claude Opus 4.6",
      category: "chat",
      type: "anthropic",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-opus-4-7",
      name: "Claude Opus 4.7",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-opus-4-8",
      name: "Claude Opus 4.8",
      category: "chat",
      type: "anthropic",
      contextLength: 1_000_000,
      maxOutputTokens: 128_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      category: "chat",
      type: "anthropic",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-sonnet-4-5-20250929",
      name: "Claude Sonnet 4.5",
      category: "chat",
      type: "anthropic",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-haiku-4-5-20251001",
      name: "Claude Haiku 4.5",
      category: "chat",
      type: "anthropic",
      contextLength: 200_000,
      maxOutputTokens: 8_192,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "claude-opus-4-5-20251101",
      name: "Claude Opus 4.5",
      category: "chat",
      type: "anthropic",
      contextLength: 200_000,
      maxOutputTokens: 64_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "Qwen3.8-Max-Preview",
      name: "Qwen3.8 Max Preview",
      category: "chat",
      contextLength: 1_000_000,
      maxOutputTokens: 32_768,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "qwen3.5-27b",
      name: "Qwen3.5 27B",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 8_192,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "qwen3.5-35b-a3b",
      name: "Qwen3.5 35B-A3B",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 8_192,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "qwen3.5-122b-a10b",
      name: "Qwen3.5 122B-A10B",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 8_192,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "qwen3.5-397b-a17b",
      name: "Qwen3.5 397B-A17B",
      category: "chat",
      contextLength: 262_144,
      maxOutputTokens: 8_192,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "grok-4.5",
      name: "Grok 4.5",
      category: "chat",
      type: "openai-responses",
      contextLength: 500_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "grok-4.3",
      name: "Grok 4.3",
      category: "chat",
      type: "openai-responses",
      contextLength: 1_000_000,
      supportsVision: true,
      supportsFunctionCall: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "grok-4.20",
      name: "Grok 4.20",
      category: "chat",
      type: "openai-responses",
      contextLength: 1_000_000,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "grok-4.20-non-reasoning",
      name: "Grok 4.20 Non-Reasoning",
      category: "chat",
      type: "openai-responses",
      contextLength: 1_000_000,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
    {
      modelKey: "grok-4.20-multi-agent",
      name: "Grok 4.20 Multi-Agent",
      category: "chat",
      type: "openai-responses",
      contextLength: 1_000_000,
      supportsVision: true,
      supportsThinking: true,
      enabled: true,
    },
    {
      modelKey: "grok-build-0.1",
      name: "Grok Build 0.1",
      category: "chat",
      type: "openai-responses",
      contextLength: 256_000,
      supportsVision: true,
      supportsFunctionCall: true,
      enabled: true,
    },
  ],
};

export const PROVIDER_PRESETS: readonly ProviderPreset[] = [
  routinAi,
  openai,
  google,
  volcengine,
  anthropic,
  siliconflow,
  xai,
  openrouter,
  deepseek,
  ollama,
];

export function findPreset(builtinId: string | null | undefined): ProviderPreset | undefined {
  if (!builtinId) return undefined;
  return PROVIDER_PRESETS.find((preset) => preset.builtinId === builtinId);
}

/** Built-in providers may declare `requiresApiKey: false`; everything else needs one. */
export function presetRequiresApiKey(builtinId: string | null | undefined): boolean {
  const preset = findPreset(builtinId);
  return preset ? (preset.requiresApiKey ?? true) : true;
}

export type { PresetModel, ProviderPreset } from "./types";
